image:
  repository: tccr.io/truecharts/esphome
  pullPolicy: IfNotPresent
  tag: v2023.5.4@sha256:9be521b99178006a84d6f09917f6d6a6df0d3f79ee674e6b9c6e25a06b272b85

securityContext:
  container:
    runAsNonRoot: false
    readOnlyRootFilesystem: false
    privileged: true
    allowPrivilegeEscalation: true
    runAsUser: 0
    runAsGroup: 0

service:
  main:
    ports:
      main:
        port: 6052
        targetPort: 6052

workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              type: http
              path: /
            readiness:
              type: http
              path: /
            startup:
              type: http
              path: /
          env:
            ESPHOME_DASHBOARD_USE_PING: false
            ESPHOME_DASHBOARD_RELATIVE_URL: /
            # ESPHOME_QUICKWIZARD:
            # ESPHOME_IS_HASSIO:
            # DISABLE_HA_AUTHENTICATION:
            # USERNAME:
            # PASSWORD:

persistence:
  config:
    enabled: true
    mountPath: /config
  platformio:
    enabled: true
    mountPath: /.platformio
portal:
  open:
    enabled: true
