image:
  repository: tccr.io/truecharts/rsshub
  pullPolicy: IfNotPresent
  tag: latest@sha256:5c05ee45940849796a83c3880d621f42d308d660bb47aa05c8d4d968092e712a
browserlessImage:
  repository: tccr.io/truecharts/browserless-chrome
  tag: 1.58.0-chrome@sha256:e77842d0a1eb20e26b6a88b95902fcba370480d2b930401ddc93f68c8d67d418
service:
  main:
    ports:
      main:
        port: 10191
# Enabled redis
redis:
  enabled: true

  redisUsername: default
additionalContainers:
  browserless:
    name: browserless
    image: "{{ .Values.browserlessImage.repository }}:{{ .Values.browserlessImage.tag }}"
    ports:
      - containerPort: 3000
        name: main
portal:
  open:
    enabled: true
securityContext:
  container:
    runAsNonRoot: false
    readOnlyRootFilesystem: false
    runAsUser: 0
    runAsGroup: 0
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            PORT: "{{ .Values.service.main.ports.main.port }}"
            NODE_ENV: production
            CACHE_TYPE: "redis"
            PUPPETEER_WS_ENDPOINT: "ws://localhost:3000"
            NODE_NAME: "{{ .Release.Name }}-{{ randAlphaNum 5 }}"
            # User  defined
            # ALLOW_ORIGIN: ""
            DISALLOW_ROBOT: false
            TITLE_LENGTH_LIMIT: 150
            REDIS_URL:
              secretKeyRef:
                expandObjectName: false
                name: '{{ printf "%s-%s" .Release.Name "rediscreds" }}'
                key: url
            HTTP_BASIC_AUTH_NAME: ""
            HTTP_BASIC_AUTH_PASS: ""
            BITBUCKET_USERNAME: ""
            BITBUCKET_PASSWORD: ""
            GITHUB_ACCESS_TOKEN: ""
            GOOGLE_FONTS_API_KEY: ""
            YOUTUBE_KEY: ""
            TELEGRAM_TOKEN: ""
            LASTFM_API_KEY: ""
