image:
  repository: tccr.io/truecharts/pihole
  pullPolicy: IfNotPresent
  tag: 2023.03.1@sha256:e48aa04bcdef84fb42f35fa2aaf54dd3ee868e2b80ab535a0ca59a8c6901453b

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    allowPrivilegeEscalation: true
    runAsUser: 0
    runAsGroup: 0
    capabilities:
      add:
        - NET_ADMIN
        - SETFCAP
        - SETPCAP
        - KILL

workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              type: http
              path: /admin/index.php
            readiness:
              type: http
              path: /admin/index.php
            startup:
              type: http
              path: /admin/index.php

envFrom:
  - configMapRef:
      name: pihole-env

service:
  main:
    ports:
      main:
        port: 9089
        targetPort: 80
  dns-tcp:
    enabled: true
    ports:
      dns-tcp:
        enabled: true
        port: 53
        targetPort: 53
  dns:
    enabled: true
    ports:
      dns:
        enabled: true
        protocol: udp
        port: 53
        targetPort: 53

pihole:
  WEBPASSWORD: "somepassword"
  DNS1: "9.9.9.9"
  DNS2: "149.112.112.112"

persistence:
  config:
    enabled: true
    mountPath: "/etc/pihole"
  dnsmasq:
    enabled: true
    mountPath: "/etc/dnsmasq.d"

portal:
  open:
    enabled: true
