image:
  repository: tccr.io/truecharts/sickgear
  pullPolicy: IfNotPresent
  tag: latest@sha256:c541e0876f23ea3c9ad3e664bf8fe961caf6182d10dadfda58cc8423461eaba8
service:
  main:
    ports:
      main:
        port: 10066
        targetPort: 8081
persistence:
  config:
    enabled: true
    mountPath: "/config"
  varrun:
    enabled: true
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            APP_DATA: /config
