image:
  repository: tccr.io/truecharts/mattermost
  tag: 7.10@sha256:83d5098172e4b79157cd1d42827e7309d1a2aba7ece58bb93686497ac22c2679
  pullPolicy: IfNotPresent

env:
  TIMEZONE: "{{ .Values.TZ }}"
  MM_SQLSETTINGS_DRIVERNAME: "postgres"
  MM_BLEVESETTINGS_INDEXDIR: "/mattermost/bleve-indexes"
  MM_SERVICESETTINGS_SITEURL: "https://test.example.com"
  MM_SQLSETTINGS_DATASOURCE:
    secretKeyRef:
      name: dbcreds
      key: urlnossl

service:
  main:
    ports:
      main:
        port: 10239
        targetPort: 8065

persistence:
  config:
    enabled: true
    mountPath: "/mattermost/config"
  data:
    enabled: true
    mountPath: "/mattermost/data"
  logs:
    enabled: true
    mountPath: "/mattermost/logs"
  plugins:
    enabled: true
    mountPath: "/mattermost/plugins"
  clientplugins:
    enabled: true
    mountPath: "/mattermost/client/plugins"
  bleveindexes:
    enabled: true
    mountPath: "/mattermost/bleve-indexes"

postgresql:
  enabled: true
  existingSecret: "dbcreds"
  postgresqlUsername: mattermost
  postgresqlDatabase: mattermost

portal:
  enabled: true
