image:
  repository: tccr.io/truecharts/budge
  tag: v0.0.9@sha256:26da88965bc10b66bd6fbcea2b8af95b761b96730249816e0b8d6f9f03ad9cbb
  pullPolicy: IfNotPresent

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0

service:
  main:
    ports:
      main:
        port: 10165
        protocol: http
        targetPort: 80

workload:
  main:
    podSpec:
      containers:
        main:
          env:
            NODE_ENV: "production"

persistence:
  config:
    enabled: true
    mountPath: /config

portal:
  open:
    enabled: true
