image:
  repository: tccr.io/truecharts/znc
  pullPolicy: IfNotPresent
  tag: v1.8.2@sha256:ccae8db985b6665477b6ded0e6070bff039693aa1ebf638f7a7edc4031921957
service:
  main:
    ports:
      main:
        targetPort: 6501
        port: 6501
persistence:
  varrun:
    enabled: true
  config:
    enabled: true
    mountPath: "/config"
portal:
  open:
    enabled: true
securityContext:
  container:
    runAsNonRoot: false
    readOnlyRootFilesystem: false
    runAsUser: 0
    runAsGroup: 0
