apiVersion: v2
kubeVersion: ">=1.16.0-0"
name: fleet
version: 7.0.19
appVersion: "2.3.3"
description: Fleet provides an online web interface which displays a set of maintained images from one or more owned repositories.
type: application
deprecated: false
home: https://truecharts.org/charts/stable/fleet
icon: https://truecharts.org/img/hotlink-ok/chart-icons/fleet.png
keywords:
  - fleet
sources:
  - https://github.com/truecharts/charts/tree/master/charts/stable/fleet
dependencies:
  - name: common
    repository: https://library-charts.truecharts.org
    version: 12.10.4
  - condition: mariadb.enabled
    name: mariadb
    repository: https://deps.truecharts.org/
    version: 7.0.34
maintainers:
  - email: info@truecharts.org
    name: TrueCharts
    url: https://truecharts.org
annotations:
  truecharts.org/catagories: |
    - incubator
  truecharts.org/SCALE-support: "true"
