image:
  repository: tccr.io/truecharts/kitchenowl-web
  pullPolicy: IfNotPresent
  tag: latest@sha256:a59332a658bc75df12fcef926b5f05efed22a1e63081481d2541e5a35213d92a
backendImage:
  repository: tccr.io/truecharts/kitchenowl-backend
  pullPolicy: IfNotPresent
  tag: latest@sha256:6799b764ebd811d9ba0785451d64b0391b2195994d093c7e6ac611420c06dc62
service:
  main:
    ports:
      main:
        protocol: http
        targetPort: 80
        port: 10246
additionalContainers:
  backend:
    name: backend
    image: "{{ .Values.backendImage.repository }}:{{ .Values.backendImage.tag }}"
    env:
      - name: FRONT_URL
        value: "{{ .Values.workload.main.podSpec.containers.main.env.FRONT_URL }}"
        # Backend also listens on 80, but afaik there is no use as of now
        # Changed port to 81 to avoid conflict with frontend
      - name: HTTP_PORT
        value: "81"
      - name: JWT_SECRET_KEY
        valueFrom:
          secretKeyRef:
            name: kitchenowl-secrets
            key: JWT_SECRET_KEY
    volumeMounts:
      - name: data
        mountPath: "/data"
persistence:
  data:
    enabled: true
    mountPath: "/data"
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            FRONT_URL: "http://localhost:10246"
            # Backend listens on 5000 websockets.
            BACK_URL: "localhost:5000"
