                    - variable: advanced
                      label: Show Advanced Settings
                      description: Advanced settings are not covered by TrueCharts Support
                      schema:
                        type: boolean
                        default: false
                        show_subquestions_if: true
                        subquestions:
                          - variable: entrypoint
                            label: (Advanced) Traefik Entrypoint
                            description: Entrypoint used by Traefik when using Traefik as Ingress Provider
                            schema:
                              type: string
                              default: websecure
                              required: true
                          - variable: ingressClassName
                            label: (Advanced/Optional) IngressClass Name
                            schema:
                              type: string
                              default: ""
                          - variable: tls
                            label: TLS-Settings
                            schema:
                              type: list
                              default: []
                              items:
                                - variable: tlsEntry
                                  label: Host
                                  schema:
                                    additional_attrs: true
                                    type: dict
                                    attrs:
                                      - variable: hosts
                                        label: Certificate Hosts
                                        schema:
                                          type: list
                                          default: []
                                          items:
                                            - variable: host
                                              label: Host
                                              schema:
                                                type: string
                                                default: ""
                                                required: true
      
                                      - variable: certificateIssuer
                                        label: Use Cert-Manager clusterIssuer
                                        description: 'add the name of your cert-manager clusterIssuer here for automatic tls certificates.'
                                        schema:
                                          type: string
                                          default: ""
                                      - variable: scaleCert
                                        label: Use TrueNAS SCALE Certificate (Deprecated)
                                        schema:
                                          show_if: [["certificateIssuer", "=", ""]]
                                          type: int
                                          $ref:
                                            - "definitions/certificate"
                                      - variable: secretName
                                        label: Use Custom Secret (Advanced)
                                        schema:
                                          show_if: [["certificateIssuer", "=", ""]]
                                          type: string
                                          default: ""
