{{/* Make sure all variables are set properly */}}
{{- include "tc.v1.common.loader.init" . -}}

{{/* Render configmaps for all pods */}}
{{- $configmaps := include "nextcloud.configmaps" . | fromYaml -}}
{{- if $configmaps -}}
  {{- $_ := mustMergeOverwrite .Values.configmap $configmaps -}}
{{- end -}}

{{/* Add [init perms] container to nextcloud */}}
{{- if not (get .Values.workload.main.podSpec "initContainers") -}}
  {{- $_ := set .Values.workload.main.podSpec "initContainers" dict -}}
{{- end -}}
{{- $initPerms := (include "nextcloud.init.perms" . | fromYaml) -}}
{{- $_ := set .Values.workload.main.podSpec.initContainers "init-perms" $initPerms -}}

{{/* Add [wait nextcloud] container to nginx */}}
{{- if not (get .Values.workload.nginx.podSpec "initContainers") -}}
  {{- $_ := set .Values.workload.nginx.podSpec "initContainers" dict -}}
{{- end -}}
{{- $waitNextcloud := (include "nextcloud.wait.nextcloud" . | fromYaml) -}}
{{- $_ := set .Values.workload.nginx.podSpec.initContainers "wait-nextcloud" $waitNextcloud -}}

{{/* Disable [notify push] if requested */}}
{{- if not .Values.nextcloud.notify_push.enabled -}}
  {{- $_ := set .Values.workload.notify "enabled" false -}}
  {{- $_ := set .Values.service.notify "enabled" false -}}
{{- else -}}
  {{/* Add [wait nextcloud] container to notify push */}}
  {{- if not (get .Values.workload.notify.podSpec "initContainers") -}}
    {{- $_ := set .Values.workload.notify.podSpec "initContainers" dict -}}
  {{- end -}}
  {{- $waitNextcloud := (include "nextcloud.wait.nextcloud" . | fromYaml) -}}
  {{- $_ := set .Values.workload.notify.podSpec.initContainers "wait-nextcloud" $waitNextcloud -}}
{{- end -}}

{{/* Disable [clamav] if requested */}}
{{- if not .Values.nextcloud.clamav.enabled -}}
  {{- $_ := set .Values.workload.clamav "enabled" false -}}
  {{- $_ := set .Values.service.clamav "enabled" false -}}
{{- end -}}

{{/* Disable [previews] if requested */}}
{{- if or (not .Values.nextcloud.previews.imaginary) (not .Values.nextcloud.previews.enabled) -}}
  {{- $_ := set .Values.workload.imaginary "enabled" false -}}
  {{- $_ := set .Values.service.imaginary "enabled" false -}}
{{- end -}}

{{/* Create [cronjobs] defined */}}
{{- $cronjobs := include "nextcloud.cronjobs" . | fromYaml -}}
{{- if $cronjobs -}}
  {{- $_ := mustMergeOverwrite .Values.workload $cronjobs -}}
{{- end -}}

{{/* TODO: fix middlewares
{{- $newMiddlewares := mustAppend .Values.ingress.main.fixedMiddlewares "tc-nextcloud-chain" -}}
{{- $_ := set .Values.ingress.main "fixedMiddlewares" $newMiddlewares -}}
*/}}
{{/* Define path for websocket
{{- define "nextcloud.hpb.ingress" -}}
{{- $fullname := include "tc.v1.common.lib.chart.names.fullname" . -}}
path: "/push/"
# -- Ignored if not kubeVersion >= 1.14-0
pathType: Prefix
service:
  # -- Overrides the service name reference for this path
  name: {{ printf "%s-hpb" $fullname }}
  port: {{ .Values.service.hpb.ports.hpb.port }}
{{- end -}}
*/}}

{{/* inject websocket path to all main ingress hosts
{{- define "nextcloud.hpb.ingressInjector" -}}
  {{- $path := list (include "nextcloud.hpb.ingress" . | fromYaml) -}}
  {{- if .Values.ingress.main.enabled -}}
    {{- range .Values.ingress.main.hosts -}}
      {{- $newpaths := list -}}
      {{- $newpaths := concat .paths $path -}}
      {{- $_ := set . "paths" ( deepCopy $newpaths ) -}}
    {{- end -}}
  {{- end -}}
{{- end -}}
*/}}
{{/* inject websocket paths in ingress
{{- include "nextcloud.hpb.ingressInjector" . -}}
*/}}

{{/* Render the templates */}}
{{- include "tc.v1.common.loader.apply" . -}}
